### ISSUE TITLE
Web Monetization Icon shows incorrect state

### ISSUE THREAD

**Issue by vezwork** [esse-dev/akita#27]
Happens especially when switching between tabs. 

May also be able to be solved alongside #17 . But that is a larger issue.

**Comment by sharon-wang** [comment]
ICON FIX:
- if its monetized, start in no tongue state which changes to tongue state
- make no tongue the default

**Comment by sharon-wang** [comment]
Action: with Akita installed, navigated to monetization-enabled site

Platform: firefox
Result: Akita icon missing

![image](https://user-images.githubusercontent.com/25834218/83935248-d4bf0980-a785-11ea-8771-a300aa84b7bf.png)

Platform: chrome
Result: Akita no tongue icon instead of tongue icon
![image](https://user-images.githubusercontent.com/25834218/83935289-4e56f780-a786-11ea-853f-3144f6a69b82.png)
