### ISSUE TITLE
Remaining changes for hackathon prototype

### ISSUE THREAD

**Issue by sharon-wang** [esse-dev/akita#41]
Circle Changes
- [x]  change circle::after to html element - @vezwork 
- [x]  change circle hover background to same colour as circle - @sharon-wang 
- [x]  get rid of XRP text from circle - @vezwork 
- [x]  add % of time spent on site to circle detail - @sharon-wang 
- [x]  add % of visits on site to circle detail - @sharon-wang 
~- [ ]  live update circle data - @vezwork~
- [x]  put website favicon in circles - @sharon-wang 
- [x]  remove click to go to site from circles - @vezwork 
- [x]  open site when you click on the circle - @sharon-wang 
- [x]  add payment stream estimate in circle detail - @sharon-wang 

Tutorial Changes
- [x]  tutorial slide 2 (tired of ads?) make image more legible/toaster ad popup animation - @vezwork 
- [x]  add link to coil on how to monetize your own site "Learn more and get involved" tutorial slide - @sharon-wang 
- [x]  add perspective on how web monetization benefits creators in tutorial slides - @sharon-wang 
- [x]  look into custom bullet points - @sharon-wang 
- [x]  higher res images for the Akita Icon tutorial slide - @vezwork 
- [x]  mention that it's the browser extension icon in Akita Icon tutorial slide - @vezwork 

General Changes
- [x]  change colour of links in akita, maybe match akita branding colours - @sharon-wang 
- [x]  add tooltip to "These monetized sites could use <3" to explain what that means - @vezwork 
- [x]  remove "https://" from sites that could use love and add favicon - @sharon-wang 
- [x]  replace needs love list with resources if user not using WM provider - @sharon-wang 

Other
- [x] Update README with demo, screenshots, tutorial explanation: https://github.com/dog-s/akita/issues/39
- [x]  test browser extension on windows (firefox, chrome) - @vezwork 
- [x]  test browser extension on mac (firefox, chrome) - @sharon-wang

**Comment by vezwork** [comment]
Favicon notes:
- maybe save icon in storage while on the site
- browsers by default expect the favicon to be at **current url**/favicon.ico, but they first check to see if there are any link tags in the html which specify where the favicon is. E.g. on https://sharonwang.netlify.app/ notice in the console that there is an error because the browser is looking for favicon.ico but cannot find it.
- http://jsfiddle.net/kh8puca6/1/ shows how to get the relative url of the favicon on a site. Favicon can then be asynchronously downloaded using fetch. Then [.blob()](https://developer.mozilla.org/en-US/docs/Web/API/Body/blob) to get a blob of the favicon which can be passed to [URL.createObjectURL()](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL). Data URLs are just strings so are easily stored, and can be displayed just by setting an html image's src to the data URL.

**Comment by sharon-wang** [comment]
Remaining changes are complete! Closing.
