### ISSUE TITLE
Load collected data and display it in the extension pop-up.

### ISSUE THREAD

**Issue by vezwork** [esse-dev/akita#6]
Our extension will passively collect data as the user browses the web. The data can be viewed in the extension icon pop-up. 

The data we display:
- time on web monetized sites.
- time on non-web monetized sites.
- number of visits to web monetized sites.
- number of visits to non-web monetized sites.
- ratio between these two times ^
- amount streamed to websites.
- top 5 sites based on: amount $$ streamed, # of visits, amount of time spent
    - top 5 in general
    - top 5 mon
    - top 5 non-mon

- FUTURE: search for amount and time spent on websites (search by website name/url)

For this task, we just want to show the data and are not concerned with aesthetics or presentation.

**Comment by vezwork** [comment]
https://www.chartjs.org/ may give us some quick, clean data visualization. At first glance, their site is really attractive and so are the charts the library produces.

**Comment by sharon-wang** [comment]
- notify user if they visit a site that was not previously monetized, but is now monetized!
- display favicon next to site with Akita data
- display a calculation of how much the user would be supporting their fave sites that are ~money the user would spend on~ currently non-monetized top sites, maybe have a running total of how much money the user could be spending based on time spent on all websites
- ratio of monetized to non-monetized sites visited, plotted over time since Akita install

**Comment by sharon-wang** [comment]
Closed by #36
