### ISSUE TITLE
[BUG] On sites with monetized AND non-monetized pages, non-monetized pages count for monetized time

### ISSUE THREAD

**Issue by vezwork** [esse-dev/akita#79]
**Describe the bug**
Once Akita sees that a site (domain) has a monetized page, it marks the entire domain as monetized. This is not accurate to how Web Monetization actually works. For example, Coil provides a mechanism for web monetizing youtube videos, once you visit a web monetized youtube video, Akita incorrectly counts ALL time on youtube as monetized time.
**To Reproduce**
1. Clear Akita data
2. Visit this web-monetized youtube video https://www.youtube.com/watch?v=sApKXmwhg4g&ab_channel=Simmer.io with an active Coil subscription and extension, and the Akita extension.
3. Spend 1 minute on the above youtube video.
4. Spend some extra time (let's say 5 mins) on other youtube videos which are not monetized. e.g. https://www.youtube.com/watch?v=F4we73GHH9k
5. Click on Akita extension icon and look at "Top monetized sites" section. Observe that youtube has 6 mins spent on it rather than 1.

**Expected behavior**
In the above reproduction Akita should only say that youtube has 1 minute spent on it, because while 6 mins were spent in total on the site, only 1 of those minutes was on a monetized page.

Akita should track both monetized and non-monetized time on a site seperately. For the purpose of the "Top monetized sites" section, only monetized time should be considered.

**Screenshots**
Unfortunately I do not have a screenshot.

**Desktop (please complete the following information):**
 - OS and Version: unknown
 - Browser and Version Chrome - version unknown

**Comment by sharon-wang** [comment]
This issue cannot be closed until https://github.com/esse-dev/akita/issues/17 is complete. It's possible for a site to have monetization enabled, but then have its payment pointer removed, however the time spent on the site would still be added to its total monetized time spent, which is not correct. If we are checking anytime the payment pointer is changed, then we will be able to differentiate between monetized time spent and non-monetized time spent in this situation.

**Comment by sharon-wang** [comment]
We can update our data storage to store monetized time spent per payment pointer per origin. Each origin will also hold the total monetized time spent at the origin in addition to the total time spent at the origin.

We currently calculate `totalMonetizedTimeSpent` and store it into `originStats`. We will need to modify how this time is being tracked so that we instead track it per payment pointer, but we still store the total time in `originStats`.

We may need to make changes to the extension popup UI, since we only display the total time spent per origin, but we may want to indicate the total monetized time spent per origin too.

**Comment by sharon-wang** [comment]
Monetized time spent will still be stored at the origin level, not at the payment pointer level, to avoid complicating the data.
