### ISSUE TITLE
[BUG] Akita doesn't know that payment is being streamed on monetized YouTube videos

### ISSUE THREAD

**Issue by sharon-wang** [esse-dev/akita#97]
**Describe the bug**
Akita doesn't know that payment is being streamed to monetized YouTube videos, even though Coil is sending payment.

**To Reproduce**
1. Have the Coil browser extension installed and login to Coil
2. Go to a web monetized youtube video such as https://www.youtube.com/watch?v=sApKXmwhg4g&ab_channel=Simmer.io
3. Spend some time watching the video (enough to make YouTube one of your Top Monetized Sites)
4. Open Akita
5. Akita shows that you've spent X amount of time on the site, but shows you the estimated payment calculation instead of the actual amount you've sent via Coil

**Expected behavior**
Akita should tell you the amount of XRP you've streamed to the site.

**Screenshots**
Despite the fact that Coil is paying to the video creator, Akita isn't aware that payment is being sent:
![image](https://user-images.githubusercontent.com/25834218/103258786-d6cffc00-4953-11eb-9823-c368feb1f8d7.png)

**Desktop (please complete the following information):**
 - OS and Version: macOS 
 - Browser: Chrome and Brave

**Additional context**
This problem is not seen on Twitch.

**Comment by vezwork** [comment]
Coil implements a special workaround for YouTube that I've heard is called "adapted sites". YouTube **does not** implement Web Monetization BUT Coil allows creators with Coil accounts to register their YouTube channel in their Coil account so that when a Coil user visits a Coil-Registered YouTube channel, payment is streamed despite the fact that there is no payment pointer on the YouTube page.

For contrast, Akita works with Twitch.tv because Twitch **does** implement Web Monetization and places Payment Pointers on Twitch videos.

Therefore, my intuition is that since this is a workaround around Web Monetization that Coil does, Coil does not actually trigger the Web Monetization JavaScript API on YouTube pages. Therefore it may not be possible to track payments to YouTube videos through Coil, since it is all done on Coil's end and not exposed to the browser.

**Comment by sharon-wang** [comment]
Twitch and YouTube are both considered "adapted sites" by Coil and Akita is able to identify that monetization is enabled on monetized YouTube videos, it's just that the incorrect data is being displayed in the UI. We're capturing that assets have been sent to the payment pointer corresponding to the YouTube video.

This is likely because the current logic only expects XRP to be sent, whereas in the case of the YouTube video, the currency is USD. So, we'll need to update `createTopSiteDetailHTML()` to handle other currencies, not just XRP.
